<a href="https://colab.research.google.com/github/nhunggnguyen04/NCKH/blob/main/Classification_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#as price

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from datasets import Value

# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/204 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_price: 0.9461
Báo cáo phân loại trên tập test as_price:
              precision    recall  f1-score   support

    Tiêu cực       0.92      0.88      0.90        25
   Trung lập       0.94      0.97      0.96       123
    Tích cực       0.96      0.93      0.95        56

    accuracy                           0.95       204
   macro avg       0.94      0.93      0.93       204
weighted avg       0.95      0.95      0.95       204

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9852
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-465

#content

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from datasets import Value

# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/640 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_content: 0.9328
Báo cáo phân loại trên tập test as_content:
              precision    recall  f1-score   support

    Tiêu cực       0.96      0.93      0.94       198
   Trung lập       0.67      0.88      0.76        59
    Tích cực       0.98      0.94      0.96       383

    accuracy                           0.93       640
   macro avg       0.87      0.92      0.89       640
weighted avg       0.94      0.93      0.94       640

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9531
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-1440

In [ ]:
df_unlabel[label_id].value_counts()

as_content_label_id
2    62365
0     9850
1     4763
Name: count, dtype: int64

#physical

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from datasets import Value

# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/816 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_physical: 0.9277
Báo cáo phân loại trên tập test as_physical:
              precision    recall  f1-score   support

    Tiêu cực       0.94      0.93      0.93       382
   Trung lập       0.82      0.80      0.81        95
    Tích cực       0.95      0.96      0.95       339

    accuracy                           0.93       816
   macro avg       0.90      0.90      0.90       816
weighted avg       0.93      0.93      0.93       816

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9363
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-861

In [ ]:
df_unlabel[label_id].value_counts()

as_physical_label_id
2    54691
0    14922
1     7365
Name: count, dtype: int64

# Packaging

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from datasets import Value

# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/378 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_packaging: 0.9339
Báo cáo phân loại trên tập test as_packaging:
              precision    recall  f1-score   support

    Tiêu cực       0.95      0.90      0.93       162
   Trung lập       0.94      0.83      0.88        18
    Tích cực       0.92      0.97      0.94       198

    accuracy                           0.93       378
   macro avg       0.94      0.90      0.92       378
weighted avg       0.93      0.93      0.93       378

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9630
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-447

In [ ]:
df_unlabel[label_id].value_counts()

as_packaging_label_id
2    59068
0    16333
1     1577
Name: count, dtype: int64

# delivery

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from datasets import Value

# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/544 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_delivery: 0.9706
Báo cáo phân loại trên tập test as_delivery:
              precision    recall  f1-score   support

    Tiêu cực       0.96      0.97      0.96        95
   Trung lập       0.93      0.96      0.94       103
    Tích cực       0.99      0.97      0.98       346

    accuracy                           0.97       544
   macro avg       0.96      0.97      0.96       544
weighted avg       0.97      0.97      0.97       544

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9743
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-1300

In [ ]:
df_unlabel[label_id].value_counts()

as_delivery_label_id
2    52749
1    21780
0     2449
Name: count, dtype: int64

In [ ]:
# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/544 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_delivery: 0.9724
Báo cáo phân loại trên tập test as_delivery:
              precision    recall  f1-score   support

    Tiêu cực       0.94      0.98      0.96        95
   Trung lập       0.93      0.96      0.95       103
    Tích cực       0.99      0.97      0.98       346

    accuracy                           0.97       544
   macro avg       0.96      0.97      0.96       544
weighted avg       0.97      0.97      0.97       544

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9724
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-2340

In [ ]:
df_unlabel[label_id].value_counts()

as_delivery_label_id
2    55125
1    18000
0     3853
Name: count, dtype: int64

In [ ]:
# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/65 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_service: 0.9231
Báo cáo phân loại trên tập test as_service:
              precision    recall  f1-score   support

    Tiêu cực       0.82      1.00      0.90        14
   Trung lập       0.88      0.88      0.88        17
    Tích cực       1.00      0.91      0.95        34

    accuracy                           0.92        65
   macro avg       0.90      0.93      0.91        65
weighted avg       0.93      0.92      0.92        65

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9692
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-130

In [ ]:
df_unlabel[label_id].value_counts()

as_service_label_id
2    60596
1     8419
0     7963
Name: count, dtype: int64