<a href="https://colab.research.google.com/github/nhunggnguyen04/NCKH/blob/main/classification_test_result.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Đánh giá mô hình gán nhãn trên từng aspect

#price

In [ ]:
# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    # Cập nhật danh sách nhãn để khớp với 4 lớp (0, 1, 2, 3)
    # 0: Tiêu cực, 1: Trung lập, 2: Tích cực, 3: Không đề cập/NaN
    class_names = ["Tiêu cực", "Trung lập", "Tích cực", "Không đề cập"]

    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/1540 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_price: 0.9851
Báo cáo phân loại trên tập test as_price:
              precision    recall  f1-score   support

    Tiêu cực       0.83      0.79      0.81        38
   Trung lập       0.86      0.88      0.87        50
    Tích cực       0.98      1.00      0.99        44
Không đề cập       0.99      0.99      0.99      1408

    accuracy                           0.99      1540
   macro avg       0.92      0.92      0.92      1540
weighted avg       0.98      0.99      0.98      1540

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9844
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-7045

In [ ]:
df_unlabel[label_id].value_counts()

as_price_label_id
3    71819
2     3958
1      768
0      433
Name: count, dtype: int64

#content

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from datasets import Value

# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/640 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_content: 0.9328
Báo cáo phân loại trên tập test as_content:
              precision    recall  f1-score   support

    Tiêu cực       0.96      0.93      0.94       198
   Trung lập       0.67      0.88      0.76        59
    Tích cực       0.98      0.94      0.96       383

    accuracy                           0.93       640
   macro avg       0.87      0.92      0.89       640
weighted avg       0.94      0.93      0.94       640

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9531
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-1440

In [ ]:
df_unlabel[label_id].value_counts()

as_content_label_id
2    62365
0     9850
1     4763
Name: count, dtype: int64

#physical

In [ ]:
# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    # Cập nhật danh sách nhãn để khớp với 4 lớp (0, 1, 2, 3)
    # 0: Tiêu cực, 1: Trung lập, 2: Tích cực, 3: Không đề cập/NaN
    class_names = ["Tiêu cực", "Trung lập", "Tích cực", "Không đề cập"]

    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/1540 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_physical: 0.9071
Báo cáo phân loại trên tập test as_physical:
              precision    recall  f1-score   support

    Tiêu cực       0.86      0.93      0.89       440
   Trung lập       0.77      0.79      0.78        76
    Tích cực       0.89      0.96      0.92       265
Không đề cập       0.96      0.89      0.93       759

    accuracy                           0.91      1540
   macro avg       0.87      0.89      0.88      1540
weighted avg       0.91      0.91      0.91      1540

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9195
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-3800

In [ ]:
df_unlabel[label_id].value_counts()

as_physical_label_id
3    41310
2    26310
0     6839
1     2519
Name: count, dtype: int64

# Packaging

In [ ]:
# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    # Cập nhật danh sách nhãn để khớp với 4 lớp (0, 1, 2, 3)
    # 0: Tiêu cực, 1: Trung lập, 2: Tích cực, 3: Không đề cập/NaN
    class_names = ["Tiêu cực", "Trung lập", "Tích cực", "Không đề cập"]

    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/1540 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_packaging: 0.9617
Báo cáo phân loại trên tập test as_packaging:
              precision    recall  f1-score   support

    Tiêu cực       0.84      0.94      0.89       200
   Trung lập       0.75      0.50      0.60        12
    Tích cực       0.92      0.96      0.94       135
Không đề cập       0.99      0.97      0.98      1193

    accuracy                           0.96      1540
   macro avg       0.87      0.84      0.85      1540
weighted avg       0.96      0.96      0.96      1540

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9675
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-3582

# delivery

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from datasets import Value

# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/544 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_delivery: 0.9706
Báo cáo phân loại trên tập test as_delivery:
              precision    recall  f1-score   support

    Tiêu cực       0.96      0.97      0.96        95
   Trung lập       0.93      0.96      0.94       103
    Tích cực       0.99      0.97      0.98       346

    accuracy                           0.97       544
   macro avg       0.96      0.97      0.96       544
weighted avg       0.97      0.97      0.97       544

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9743
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-1300

In [ ]:
df_unlabel[label_id].value_counts()

as_delivery_label_id
2    52749
1    21780
0     2449
Name: count, dtype: int64

In [ ]:
# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics (using None in Python)
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    class_names = ["Tiêu cực", "Trung lập", "Tích cực"]
    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/544 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_delivery: 0.9724
Báo cáo phân loại trên tập test as_delivery:
              precision    recall  f1-score   support

    Tiêu cực       0.94      0.98      0.96        95
   Trung lập       0.93      0.96      0.95       103
    Tích cực       0.99      0.97      0.98       346

    accuracy                           0.97       544
   macro avg       0.96      0.97      0.96       544
weighted avg       0.97      0.97      0.97       544

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9724
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-2340

In [ ]:
df_unlabel[label_id].value_counts()

as_delivery_label_id
2    55125
1    18000
0     3853
Name: count, dtype: int64

# Service

In [ ]:
# Ensure the label column is named 'labels' for the trainer to recognize it as ground truth
if LABEL_COL in tokenized_test.column_names:
    tokenized_test_final = tokenized_test.rename_column(LABEL_COL, "labels")
else:
    tokenized_test_final = tokenized_test

# Cast the labels to int64 to avoid NotImplementedError for Float
tokenized_test_final = tokenized_test_final.cast_column("labels", Value("int64"))

# Predict using the renamed dataset
test_results = trainer.predict(tokenized_test_final)
pred_labels = np.argmax(test_results.predictions, axis=1)
true_labels = test_results.label_ids

# Check if true_labels exist before calculating metrics
if true_labels is not None:
    test_acc = accuracy_score(true_labels, pred_labels)
    print(f"Độ chính xác (accuracy) trên tập test {LABEL_COL}: {test_acc:.4f}")

    # Cập nhật danh sách nhãn để khớp với 4 lớp (0, 1, 2, 3)
    # 0: Tiêu cực, 1: Trung lập, 2: Tích cực, 3: Không đề cập/NaN
    class_names = ["Tiêu cực", "Trung lập", "Tích cực", "Không đề cập"]

    print(f"Báo cáo phân loại trên tập test {LABEL_COL}:")
    print(classification_report(true_labels, pred_labels, target_names=class_names))
else:
    print("Lỗi: Không tìm thấy nhãn thực tế (true labels) trong dataset.")

Casting the dataset:   0%|          | 0/1540 [00:00<?, ? examples/s]

Độ chính xác (accuracy) trên tập test as_service: 0.9760
Báo cáo phân loại trên tập test as_service:
              precision    recall  f1-score   support

    Tiêu cực       0.87      0.84      0.86        88
   Trung lập       1.00      0.89      0.94         9
    Tích cực       0.79      0.91      0.85        33
Không đề cập       0.99      0.99      0.99      1410

    accuracy                           0.98      1540
   macro avg       0.91      0.91      0.91      1540
weighted avg       0.98      0.98      0.98      1540

In [ ]:
# Lưu lại mô hình đã được fine-tune (tốt nhất) và tokenizer
trainer.save_model("./best_phobert_model")
tokenizer.save_pretrained("./best_phobert_model")

# In ra kết quả mô hình tốt nhất trên tập validation
best_acc = trainer.state.best_metric
print(f"Độ chính xác tốt nhất trên tập validation: {best_acc:.4f}")
print("Checkpoint mô hình tốt nhất được lưu tại:", trainer.state.best_model_checkpoint)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Độ chính xác tốt nhất trên tập validation: 0.9708
Checkpoint mô hình tốt nhất được lưu tại: ./sentiment_class/checkpoint-7055

In [ ]:
df_unlabel[label_id].value_counts()

as_service_label_id
3    72824
2     3187
0      902
1       65
Name: count, dtype: int64