<a href="https://colab.research.google.com/github/nhunggnguyen04/NCKH/blob/main/Preprocessing_data_for_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import thư viện cần thiết
import pandas as pd

# Nhập dữ liệu và tiền xử lý dữ liệu

In [2]:
# Lấy dataset về bình luận đã gán nhãn và tính điểm cảm xúc của từng sản phẩm
df = pd.read_csv('/content/tiki_reviews_with_sentiment_final.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76978 entries, 0 to 76977
Data columns (total 42 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   product_id                    76978 non-null  int64
 1   review_id                     76978 non-null  int64
 2   rating                        76978 non-null  int64
 3   content                       76977 non-null  object
 4   likes                         76978 non-null  int64
 5   customer_name                 75635 non-null  object
 6   created_at                    76978 non-null  int64
 7   segmented_content             76977 non-null  object
 8   as_content_label_id           76978 non-null  int64
 9   as_content_score_negative     76978 non-null  float64
 10  as_content_score_neutral      76978 non-null  float64
 11  as_content_score_positive     76978 non-null  float64
 12  as_content_score_na           76978 non-null  float64
 13  as_physical_label_id          76978 non-null  int64
 14  as_physical_score_negative    76978 non-null  float64
 15  as_physical_score_neutral     76978 non-null  float64
 16  as_physical_score_positive    76978 non-null  float64
 17  as_physical_score_na          76978 non-null  float64
 18  as_price_label_id             76978 non-null  int64
 19  as_price_score_negative       76978 non-null  float64
 20  as_price_score_neutral        76978 non-null  float64
 21  as_price_score_positive       76978 non-null  float64
 22  as_price_score_na             76978 non-null  float64
 23  as_packaging_label_id         76978 non-null  int64
 24  as_packaging_score_negative   76978 non-null  float64
 25  as_packaging_score_neutral    76978 non-null  float64
 26  as_packaging_score_positive   76978 non-null  float64
 27  as_packaging_score_na         76978 non-null  float64
 28  as_delivery_label_id          76978 non-null  int64
 29  as_delivery_score_negative    76978 non-null  float64
 30  as_delivery_score_neutral     76978 non-null  float64
 31  as_delivery_score_positive    76978 non-null  float64
 32  as_delivery_score_na          76978 non-null  float64
 33  as_service_label_id           76978 non-null  int64
 34  as_service_score_negative     76978 non-null  float64
 35  as_service_score_neutral      76978 non-null  float64
 36  as_service_score_positive     76978 non-null  float64
 37  as_service_score_na           76978 non-null  float64
 38  sentiment_llm_label_id        76978 non-null  int64
 39  sentiment_llm_score_negative  76978 non-null  float64
 40  sentiment_llm_score_neutral   76978 non-null  float64
 41  sentiment_llm_score_positive  76978 non-null  float64
dtypes: float64(27), int64(12), object(3)
memory usage: 24.7+ MB

In [3]:
label_cols = ['as_content_label_id', 'as_physical_label_id', 'as_price_label_id', 'as_packaging_label_id', 'as_delivery_label_id', 'as_service_label_id','sentiment_llm_label_id']

def get_sentiment_counts(df, col):
    # Pivot table to count occurrences of each label (0, 1, 2)
    counts = df.groupby(['product_id', col]).size().unstack(fill_value=0)
    # Rename columns to reflect the aspect and sentiment
    counts.columns = [f'{col}_{sent}' for sent in counts.columns]
    return counts

# Aggregate all label columns
agg_results = []
for col in label_cols:
    agg_results.append(get_sentiment_counts(df, col))

# Combine all aggregated results
df_aspect_sentiment = pd.concat(agg_results, axis=1).reset_index()

display(df_aspect_sentiment.head())
df_aspect_sentiment.info()

,product_id,as_content_label_id_0,as_content_label_id_1,as_content_label_id_2,as_content_label_id_3,as_physical_label_id_0,as_physical_label_id_1,as_physical_label_id_2,as_physical_label_id_3,as_price_label_id_0,...,as_delivery_label_id_1,as_delivery_label_id_2,as_delivery_label_id_3,as_service_label_id_0,as_service_label_id_1,as_service_label_id_2,as_service_label_id_3,sentiment_llm_label_id_0,sentiment_llm_label_id_1,sentiment_llm_label_id_2
0,335337,3,4,82,105,11,2,56,125,0,...,2,44,143,5,0,10,179,19,33,142
1,347334,1,5,83,113,19,10,70,103,2,...,3,47,147,1,0,10,191,24,25,153
2,356317,0,0,6,2,0,0,0,8,0,...,0,0,8,0,0,0,8,0,0,8
3,377644,5,12,105,59,4,1,32,144,1,...,0,34,145,1,0,6,174,8,32,141
4,381533,0,0,8,4,1,0,1,10,0,...,0,0,12,0,0,0,12,1,0,11

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1435 entries, 0 to 1434
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   product_id                1435 non-null   int64
 1   as_content_label_id_0     1435 non-null   int64
 2   as_content_label_id_1     1435 non-null   int64
 3   as_content_label_id_2     1435 non-null   int64
 4   as_content_label_id_3     1435 non-null   int64
 5   as_physical_label_id_0    1435 non-null   int64
 6   as_physical_label_id_1    1435 non-null   int64
 7   as_physical_label_id_2    1435 non-null   int64
 8   as_physical_label_id_3    1435 non-null   int64
 9   as_price_label_id_0       1435 non-null   int64
 10  as_price_label_id_1       1435 non-null   int64
 11  as_price_label_id_2       1435 non-null   int64
 12  as_price_label_id_3       1435 non-null   int64
 13  as_packaging_label_id_0   1435 non-null   int64
 14  as_packaging_label_id_1   1435 non-null   int64
 15  as_packaging_label_id_2   1435 non-null   int64
 16  as_packaging_label_id_3   1435 non-null   int64
 17  as_delivery_label_id_0    1435 non-null   int64
 18  as_delivery_label_id_1    1435 non-null   int64
 19  as_delivery_label_id_2    1435 non-null   int64
 20  as_delivery_label_id_3    1435 non-null   int64
 21  as_service_label_id_0     1435 non-null   int64
 22  as_service_label_id_1     1435 non-null   int64
 23  as_service_label_id_2     1435 non-null   int64
 24  as_service_label_id_3     1435 non-null   int64
 25  sentiment_llm_label_id_0  1435 non-null   int64
 26  sentiment_llm_label_id_1  1435 non-null   int64
 27  sentiment_llm_label_id_2  1435 non-null   int64
dtypes: int64(28)
memory usage: 314.0 KB

In [4]:
# Lấy dataset về dữ liệu sản phẩm
df_prod=pd.read_csv('/content/tiki_product.csv')
display(df_prod)

,ID,Seller ID,Name,Price (After Discount),Price (Before Discount),Sales Count,Rating Average,Number Reviews,Discount Rate,URL
0,270880693,2953,Ai Tăng Lương Cho Bạn? 3 Bí Quyết Đơn Giản Để ...,169000,199000,1518,4.8,53,15,https://tiki.vn/ai-tang-luong-cho-ban-3-bi-quy...
1,271518926,1,Sách Dám bị ghét,83300,119000,1424,5.0,59,30,https://tiki.vn/sach-dam-bi-ghet-p271518926.ht...
2,278398007,2953,Sách - Sống Đời Rủng Rỉnh Thong Dong - Quán Xu...,169000,199000,142,5.0,9,15,https://tiki.vn/sach-song-doi-rung-rinh-thong-...
3,276960030,1,Sách Khi Mọi Điều Không Như Ý,70850,109000,2491,5.0,112,35,https://tiki.vn/sach-khi-moi-dieu-khong-nhu-y-...
4,403896,9988,Sách Đại Việt Sử Ký Toàn Thư,236350,236350,738,4.7,74,0,https://tiki.vn/sach-dai-viet-su-ky-toan-thu-p...
...,...,...,...,...,...,...,...,...,...,...
1645,92859060,1,Sách Tam Thể 3 - Tử Thần Sống Mãi,248500,355000,1937,4.8,305,30,https://tiki.vn/sach-tam-the-3-tu-than-song-ma...
1646,53789573,53660,Sách Bến Xe (Tái Bản 2020),59200,76000,203,5.0,94,22,https://tiki.vn/sach-ben-xe-tai-ban-2020-p5378...
1647,33492447,1,Sách Mục Tiêu,162700,229000,2262,4.7,133,29,https://tiki.vn/sach-muc-tieu-p33492447.html?s...
1648,3608625,7446,Sách Payback Time - Ngày Đòi Nợ,299000,299000,32117,4.8,4449,0,https://tiki.vn/sach-payback-time-ngay-doi-no-...
1649,543206,1,Sách Không Gia Đình (Bìa Cứng),95000,136000,492,4.3,9,30,https://tiki.vn/sach-khong-gia-dinh-bia-cung-p...

In [5]:
# Hợp nhất dữ liệu vào cùng một bảng
merged_df = df_prod.merge(df_aspect_sentiment, left_on='ID', right_on='product_id', how='left')
display(merged_df.head(5))

,ID,Seller ID,Name,Price (After Discount),Price (Before Discount),Sales Count,Rating Average,Number Reviews,Discount Rate,URL,...,as_delivery_label_id_1,as_delivery_label_id_2,as_delivery_label_id_3,as_service_label_id_0,as_service_label_id_1,as_service_label_id_2,as_service_label_id_3,sentiment_llm_label_id_0,sentiment_llm_label_id_1,sentiment_llm_label_id_2
0,270880693,2953,Ai Tăng Lương Cho Bạn? 3 Bí Quyết Đơn Giản Để ...,169000,199000,1518,4.8,53,15,https://tiki.vn/ai-tang-luong-cho-ban-3-bi-quy...,...,0.0,7.0,23.0,0.0,0.0,0.0,30.0,2.0,4.0,24.0
1,271518926,1,Sách Dám bị ghét,83300,119000,1424,5.0,59,30,https://tiki.vn/sach-dam-bi-ghet-p271518926.ht...,...,0.0,4.0,11.0,0.0,0.0,1.0,14.0,1.0,1.0,13.0
2,278398007,2953,Sách - Sống Đời Rủng Rỉnh Thong Dong - Quán Xu...,169000,199000,142,5.0,9,15,https://tiki.vn/sach-song-doi-rung-rinh-thong-...,...,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
3,276960030,1,Sách Khi Mọi Điều Không Như Ý,70850,109000,2491,5.0,112,35,https://tiki.vn/sach-khi-moi-dieu-khong-nhu-y-...,...,0.0,5.0,24.0,0.0,0.0,0.0,29.0,2.0,6.0,21.0
4,403896,9988,Sách Đại Việt Sử Ký Toàn Thư,236350,236350,738,4.7,74,0,https://tiki.vn/sach-dai-viet-su-ky-toan-thu-p...,...,6.0,63.0,171.0,4.0,0.0,15.0,231.0,47.0,47.0,156.0

In [6]:
merged_df.to_csv('merged_df.csv', index=False)

In [7]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650 entries, 0 to 1649
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        1650 non-null   int64
 1   Seller ID                 1650 non-null   int64
 2   Name                      1650 non-null   object
 3   Price (After Discount)    1650 non-null   int64
 4   Price (Before Discount)   1650 non-null   int64
 5   Sales Count               1650 non-null   int64
 6   Rating Average            1650 non-null   float64
 7   Number Reviews            1650 non-null   int64
 8   Discount Rate             1650 non-null   int64
 9   URL                       1650 non-null   object
 10  product_id                1435 non-null   float64
 11  as_content_label_id_0     1435 non-null   float64
 12  as_content_label_id_1     1435 non-null   float64
 13  as_content_label_id_2     1435 non-null   float64
 14  as_content_label_id_3     1435 non-null   float64
 15  as_physical_label_id_0    1435 non-null   float64
 16  as_physical_label_id_1    1435 non-null   float64
 17  as_physical_label_id_2    1435 non-null   float64
 18  as_physical_label_id_3    1435 non-null   float64
 19  as_price_label_id_0       1435 non-null   float64
 20  as_price_label_id_1       1435 non-null   float64
 21  as_price_label_id_2       1435 non-null   float64
 22  as_price_label_id_3       1435 non-null   float64
 23  as_packaging_label_id_0   1435 non-null   float64
 24  as_packaging_label_id_1   1435 non-null   float64
 25  as_packaging_label_id_2   1435 non-null   float64
 26  as_packaging_label_id_3   1435 non-null   float64
 27  as_delivery_label_id_0    1435 non-null   float64
 28  as_delivery_label_id_1    1435 non-null   float64
 29  as_delivery_label_id_2    1435 non-null   float64
 30  as_delivery_label_id_3    1435 non-null   float64
 31  as_service_label_id_0     1435 non-null   float64
 32  as_service_label_id_1     1435 non-null   float64
 33  as_service_label_id_2     1435 non-null   float64
 34  as_service_label_id_3     1435 non-null   float64
 35  sentiment_llm_label_id_0  1435 non-null   float64
 36  sentiment_llm_label_id_1  1435 non-null   float64
 37  sentiment_llm_label_id_2  1435 non-null   float64
dtypes: float64(29), int64(7), object(2)
memory usage: 490.0+ KB



> Dữ liệu cột 10-16 đang bị thiếu giá trị, do các sản phẩm có lượt bán thấp, không có bình luận vì vậy kết quả trả về sẽ là cột trống. Nhóm nghiên cứu sẽ xoá các dòng không chứa dữ liệu này

In [8]:
# Xoá dữ liệu trống
merged_df.dropna(subset=['product_id'],inplace=True)
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1435 entries, 0 to 1649
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        1435 non-null   int64
 1   Seller ID                 1435 non-null   int64
 2   Name                      1435 non-null   object
 3   Price (After Discount)    1435 non-null   int64
 4   Price (Before Discount)   1435 non-null   int64
 5   Sales Count               1435 non-null   int64
 6   Rating Average            1435 non-null   float64
 7   Number Reviews            1435 non-null   int64
 8   Discount Rate             1435 non-null   int64
 9   URL                       1435 non-null   object
 10  product_id                1435 non-null   float64
 11  as_content_label_id_0     1435 non-null   float64
 12  as_content_label_id_1     1435 non-null   float64
 13  as_content_label_id_2     1435 non-null   float64
 14  as_content_label_id_3     1435 non-null   float64
 15  as_physical_label_id_0    1435 non-null   float64
 16  as_physical_label_id_1    1435 non-null   float64
 17  as_physical_label_id_2    1435 non-null   float64
 18  as_physical_label_id_3    1435 non-null   float64
 19  as_price_label_id_0       1435 non-null   float64
 20  as_price_label_id_1       1435 non-null   float64
 21  as_price_label_id_2       1435 non-null   float64
 22  as_price_label_id_3       1435 non-null   float64
 23  as_packaging_label_id_0   1435 non-null   float64
 24  as_packaging_label_id_1   1435 non-null   float64
 25  as_packaging_label_id_2   1435 non-null   float64
 26  as_packaging_label_id_3   1435 non-null   float64
 27  as_delivery_label_id_0    1435 non-null   float64
 28  as_delivery_label_id_1    1435 non-null   float64
 29  as_delivery_label_id_2    1435 non-null   float64
 30  as_delivery_label_id_3    1435 non-null   float64
 31  as_service_label_id_0     1435 non-null   float64
 32  as_service_label_id_1     1435 non-null   float64
 33  as_service_label_id_2     1435 non-null   float64
 34  as_service_label_id_3     1435 non-null   float64
 35  sentiment_llm_label_id_0  1435 non-null   float64
 36  sentiment_llm_label_id_1  1435 non-null   float64
 37  sentiment_llm_label_id_2  1435 non-null   float64
dtypes: float64(29), int64(7), object(2)
memory usage: 437.2+ KB

In [9]:
# Xoá cột không cần thiết
merged_df.drop(columns=['Seller ID','Name','URL','product_id','Price (After Discount)'],inplace=True)

In [10]:
display(merged_df)

,ID,Price (Before Discount),Sales Count,Rating Average,Number Reviews,Discount Rate,as_content_label_id_0,as_content_label_id_1,as_content_label_id_2,as_content_label_id_3,...,as_delivery_label_id_1,as_delivery_label_id_2,as_delivery_label_id_3,as_service_label_id_0,as_service_label_id_1,as_service_label_id_2,as_service_label_id_3,sentiment_llm_label_id_0,sentiment_llm_label_id_1,sentiment_llm_label_id_2
0,270880693,199000,1518,4.8,53,15,2.0,1.0,21.0,6.0,...,0.0,7.0,23.0,0.0,0.0,0.0,30.0,2.0,4.0,24.0
1,271518926,119000,1424,5.0,59,30,0.0,1.0,5.0,9.0,...,0.0,4.0,11.0,0.0,0.0,1.0,14.0,1.0,1.0,13.0
2,278398007,199000,142,5.0,9,15,0.0,0.0,2.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
3,276960030,109000,2491,5.0,112,35,1.0,1.0,13.0,14.0,...,0.0,5.0,24.0,0.0,0.0,0.0,29.0,2.0,6.0,21.0
4,403896,236350,738,4.7,74,0,4.0,8.0,74.0,164.0,...,6.0,63.0,171.0,4.0,0.0,15.0,231.0,47.0,47.0,156.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,92859060,355000,1937,4.8,305,30,1.0,4.0,37.0,78.0,...,2.0,36.0,77.0,0.0,1.0,1.0,118.0,23.0,18.0,79.0
1646,53789573,76000,203,5.0,94,22,2.0,14.0,70.0,187.0,...,4.0,94.0,171.0,2.0,1.0,7.0,263.0,50.0,57.0,166.0
1647,33492447,229000,2262,4.7,133,29,2.0,1.0,19.0,27.0,...,1.0,9.0,37.0,1.0,0.0,1.0,47.0,10.0,5.0,34.0
1648,3608625,299000,32117,4.8,4449,0,10.0,18.0,145.0,140.0,...,9.0,75.0,220.0,4.0,0.0,29.0,280.0,63.0,34.0,216.0
1649,543206,136000,492,4.3,9,30,1.0,0.0,8.0,8.0,...,1.0,4.0,12.0,0.0,0.0,0.0,17.0,5.0,2.0,10.0